name: Generate Sitemap

on:
  push:
    branches:
      - main

# Cấp quyền ghi vào repository cho GitHub Actions (Sửa lỗi exit code 128)
permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate Sitemap
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: 'https://hongphong214365.github.io/'
          # Nếu bạn muốn loại trừ trang nào, dùng exclude-paths thay cho ignore-files-at-root:
          # exclude-paths: '/test.html /admin/'
